### get all users
GET http://localhost:3000/users

#### get user by id
GET http://localhost:3000/users/653beaa297cc8a1aaa0396e7

#### create user
POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{
    "email": "test@example.com",
    "username": "test@test.com",
    "name": "Daniel",
    "ipaddress": "94.121.163.63"
}

#### update user
PUT http://localhost:3000/users/653beaa297cc8a1aaa0396e7 HTTP/1.1
Content-Type: application/json

{
    "email": "emery@example.com",
    "username": "test@test.com",
    "name": "Hello",
    "ipaddress": "94.121.163.63"
}

###delete user
PUT http://localhost:3000/users/6543e15f9af3b3ab918ba848

###